### ISSUE TITLE
客服评价在dialog样式下不能正常发送

### ISSUE THREAD

**Issue by ZhaoNingqiang** [easemob/kefu-android-demo#40]
之前用im的sdk做的客服功能，新改到客服专用的sdk后，在dialog中评价客服不能正常回调，用Activity可以正常发送，但如果Activity的主题改成Dialog后，又发送不出去，走不到回调中。调用客服评价的方法为： public static void sendEvalMessage(String msgId, String summary, String detail, final Callback callback)；之前用im的sdk做同样的功能正常。

**Comment by liyuzhao** [comment]
看下demo，没有遇到回调失败的情况。
