### ISSUE TITLE
广播未注册，退出时报错

### ISSUE THREAD

**Issue by fxd09151129** [easemob/kefu-android-demo#41]
java.lang.IllegalArgumentException: Receiver not registered: com.hyphenate.chat.CountDownBroadCast
  at com.hyphenate.chat.ChatManager.unregisterCountDown(ChatManager.java:273)

void unregisterCountDown() {

        if(this.broadCastReceiver != null) {
            EMClient.getInstance().getContext().unregisterReceiver(this.broadCastReceiver);
        }

    }

**Comment by Ashye** [comment]
我也碰到了，这个问题官方要 修正不？

**Comment by liyuzhao** [comment]
thx, 新版本已修复
